git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  theme:
    activeBorderColor:
      - '#F79A16'
      - bold
    inactiveBorderColor:
      - '#81B56B'
    optionsTextColor:
      - '#AEEEFC'
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - reverse
